name: 问题提交
description: 提交一个发现的问题
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: |
        请描述一下具体问题
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 问题发生在第几章第几节
      description: |
        提供章节，错误信息log
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 有解决办法么？
    validations:
      required: false


  - type: textarea
    id: osVersion
    attributes:
      label: 测试用的Mysql版本
      value: |
        <details>

        ```console
        # On Linux:
        $ sh-4.4# mysql --version
        mysql  Ver 8.0.32 for Linux on aarch64 (MySQL Community Server - GPL)
   
        </details>


